# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    memcached.servers:
      - { host: 127.0.0.1, port: 11211 }

services:
    memcached:
        class: Memcached
        calls:
            - [ addServers, [ %memcached.servers% ]]